"""add_skipped_questions_tracking

Revision ID: 143fb069d2ff
Revises: df0746987e94
Create Date: 2026-02-05 07:21:24.719054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '143fb069d2ff'
down_revision: Union[str, Sequence[str], None] = 'df0746987e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {column["name"] for column in inspector.get_columns("interview_sessions")}

    if "questions_answered" not in columns:
        op.add_column('interview_sessions', sa.Column('questions_answered', sa.Integer(), nullable=True))
    if "questions_skipped" not in columns:
        op.add_column('interview_sessions', sa.Column('questions_skipped', sa.Integer(), nullable=True))
    if "skipped_categories" not in columns:
        op.add_column('interview_sessions', sa.Column('skipped_categories', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'skipped_categories')
    op.drop_column('interview_sessions', 'questions_skipped')
    op.drop_column('interview_sessions', 'questions_answered')
    # ### end Alembic commands ###
