"""api_organization

Revision ID: 1c749d65c84e
Revises: df0746987e94
Create Date: 2026-02-05 09:18:02.060011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c749d65c84e'
down_revision: Union[str, Sequence[str], None] = 'df0746987e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.add_column('api_keys', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'organizations', ['organization_id'], ['id'])
    op.drop_column('api_keys', 'organization')
    op.add_column('interview_sessions', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_interview_sessions_organization_id'), 'interview_sessions', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'interview_sessions', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_interview_sessions_organization_id'), table_name='interview_sessions')
    op.drop_column('interview_sessions', 'organization_id')
    op.add_column('api_keys', sa.Column('organization', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_column('api_keys', 'organization_id')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
