"""add_background_task_table

Revision ID: 2644a6aea001
Revises: 839991411da5
Create Date: 2026-02-13 13:50:12.343017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2644a6aea001'
down_revision: Union[str, Sequence[str], None] = '839991411da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('related_entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('related_entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_tasks_related_entity_id'), 'background_tasks', ['related_entity_id'], unique=False)
    op.create_index(op.f('ix_background_tasks_status'), 'background_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_background_tasks_task_type'), 'background_tasks', ['task_type'], unique=False)
    op.drop_index(op.f('uq_candidate_email_org'), table_name='candidate', postgresql_where='(email IS NOT NULL)')
    op.add_column('candidate_profile_summaries', sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profile_summaries', 'session_id')
    op.create_index(op.f('uq_candidate_email_org'), 'candidate', ['email', 'organization_id'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.drop_index(op.f('ix_background_tasks_task_type'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_status'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_related_entity_id'), table_name='background_tasks')
    op.drop_table('background_tasks')
    # ### end Alembic commands ###
