"""add_domain_infra_context_and_candidate_summary_models

Revision ID: 3cdcb6bf6537
Revises: 5eb59ab553ea
Create Date: 2026-01-19 13:58:16.212408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3cdcb6bf6537'
down_revision: Union[str, Sequence[str], None] = '5eb59ab553ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profile_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructure_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infrastructure_contexts')
    op.drop_table('domain_contexts')
    op.drop_table('candidate_profile_summaries')
    # ### end Alembic commands ###
