"""alter_candidate_model_add_email_and_organization

Revision ID: 50b9546ecded
Revises: 1119b51e758d
Create Date: 2026-02-11 17:19:28.541871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50b9546ecded'
down_revision: Union[str, Sequence[str], None] = '1119b51e758d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('email', sa.String(), nullable=True))
    op.add_column('candidate', sa.Column('organization_id', sa.Integer(), nullable=True))
    # Create a partial unique index scoped by organization.
    # Uniqueness is per (email, organization_id), and NULL emails are allowed.
    op.create_index('uq_candidate_email_org', 'candidate', ['email', 'organization_id'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    # Name the foreign key constraint so downgrades can drop it reliably.
    op.create_foreign_key('fk_candidate_organization', 'candidate', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the named index/constraint first, then columns.
    op.drop_index('uq_candidate_email_org', table_name='candidate')
    op.drop_constraint('fk_candidate_organization', 'candidate', type_='foreignkey')
    op.drop_column('candidate', 'organization_id')
    op.drop_column('candidate', 'email')
    # ### end Alembic commands ###
