"""Add name to candidate table

Revision ID: 5776275e4bfb
Revises: b5707da92b16
Create Date: 2025-12-31 12:28:03.251166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5776275e4bfb'
down_revision: Union[str, Sequence[str], None] = 'b5707da92b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first to handle existing rows
    op.add_column('candidate', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Update existing rows with a default value
    op.execute("UPDATE candidate SET name = 'Unknown' WHERE name IS NULL")

    # Now make the column NOT NULL
    op.alter_column('candidate', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'name')
    # ### end Alembic commands ###
