"""add predefined roles, question sets, and questions

Revision ID: 583c6a7617ce
Revises: d5ac286b4eaa
Create Date: 2026-01-07 15:46:27.547663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '583c6a7617ce'
down_revision: Union[str, Sequence[str], None] = 'd5ac286b4eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --------------------------------------------------------------------
# Postgres ENUM — keep global and idempotent (minimal change)
# --------------------------------------------------------------------
seniority_enum = postgresql.ENUM(
    'JUNIOR', 'MID', 'SENIOR', 'LEAD', 'PRINCIPAL', name='senioritylevel', create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure enum exists (safe for fresh & existing DBs)
    seniority_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - adjusted minimally ###
    bind = op.get_bind()
    insp = sa.inspect(bind)

    if not insp.has_table('predefined_roles'):
        op.create_table('predefined_roles',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('level', seniority_enum, nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_predefined_roles_is_active'), 'predefined_roles', ['is_active'], unique=False)
        op.create_index(op.f('ix_predefined_roles_level'), 'predefined_roles', ['level'], unique=False)
        op.create_index(op.f('ix_predefined_roles_name'), 'predefined_roles', ['name'], unique=False)

    if not insp.has_table('predefined_question_sets'):
        op.create_table('predefined_question_sets',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('role_id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['predefined_roles.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_predefined_question_sets_is_active'), 'predefined_question_sets', ['is_active'], unique=False)
        op.create_index(op.f('ix_predefined_question_sets_role_id'), 'predefined_question_sets', ['role_id'], unique=False)

    if not insp.has_table('predefined_questions'):
        op.create_table('predefined_questions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('question_set_id', sa.Uuid(), nullable=False),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('what_assesses', sa.JSON(), nullable=True),
        sa.Column('expected_answer_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('is_required', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['question_set_id'], ['predefined_question_sets.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_predefined_questions_category'), 'predefined_questions', ['category'], unique=False)
        op.create_index(op.f('ix_predefined_questions_order'), 'predefined_questions', ['order'], unique=False)
        op.create_index(op.f('ix_predefined_questions_question_set_id'), 'predefined_questions', ['question_set_id'], unique=False)

    # cleanup legacy checkpoint tables only if they exist
    if insp.has_table('checkpoint_blobs'):
        try:
            op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
        except Exception:
            pass
        op.drop_table('checkpoint_blobs')
    if insp.has_table('checkpoints'):
        try:
            op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
        except Exception:
            pass
        op.drop_table('checkpoints')
    if insp.has_table('checkpoint_writes'):
        try:
            op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
        except Exception:
            pass
        op.drop_table('checkpoint_writes')
    if insp.has_table('checkpoint_migrations'):
        op.drop_table('checkpoint_migrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.drop_index(op.f('ix_predefined_questions_question_set_id'), table_name='predefined_questions')
    op.drop_index(op.f('ix_predefined_questions_order'), table_name='predefined_questions')
    op.drop_index(op.f('ix_predefined_questions_category'), table_name='predefined_questions')
    op.drop_table('predefined_questions')
    op.drop_index(op.f('ix_predefined_question_sets_role_id'), table_name='predefined_question_sets')
    op.drop_index(op.f('ix_predefined_question_sets_is_active'), table_name='predefined_question_sets')
    op.drop_table('predefined_question_sets')
    op.drop_index(op.f('ix_predefined_roles_name'), table_name='predefined_roles')
    op.drop_index(op.f('ix_predefined_roles_level'), table_name='predefined_roles')
    op.drop_index(op.f('ix_predefined_roles_is_active'), table_name='predefined_roles')
    op.drop_table('predefined_roles')
    # ### end Alembic commands ###
