"""add mode and question_set_id to interview sessions

Revision ID: 5eb59ab553ea
Revises: 583c6a7617ce
Create Date: 2026-01-13 09:17:04.939415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5eb59ab553ea'
down_revision: Union[str, Sequence[str], None] = '583c6a7617ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add mode column with default value for backward compatibility
    op.add_column('interview_sessions', sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), server_default='dynamic_gap', nullable=False))

    # Add question_set_id column (nullable for dynamic_gap mode) - UUID type to match predefined_question_sets.id
    op.add_column('interview_sessions', sa.Column('question_set_id', sa.Uuid(), nullable=True))

    # Create index on mode for efficient filtering
    op.create_index(op.f('ix_interview_sessions_mode'), 'interview_sessions', ['mode'], unique=False)

    # Create foreign key to predefined_question_sets
    op.create_foreign_key('fk_interview_session_question_set', 'interview_sessions', 'predefined_question_sets', ['question_set_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # Drop foreign key constraint
    op.drop_constraint('fk_interview_session_question_set', 'interview_sessions', type_='foreignkey')

    # Drop index
    op.drop_index(op.f('ix_interview_sessions_mode'), table_name='interview_sessions')

    # Drop columns
    op.drop_column('interview_sessions', 'question_set_id')
    op.drop_column('interview_sessions', 'mode')


# Removed old downgrade code that recreates tables from other branch
def _old_downgrade() -> None:
    """Original autogenerated downgrade (kept for reference)."""
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('interview_sessions2',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_set_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resume_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resume_extracted_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questions_asked', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questions_skipped', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skipped_question_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('termination_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('average_pattern_match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_completeness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], name='interview_sessions2_candidate_id_fkey'),
    sa.ForeignKeyConstraint(['question_set_id'], ['predefined_question_sets.id'], name='interview_sessions2_question_set_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['predefined_roles.id'], name='interview_sessions2_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='interview_sessions2_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('answered_questions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pattern_match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('completeness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('assessment_coverage', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('missing_elements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('scoring_reasoning', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extracted_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['predefined_questions.id'], name=op.f('answered_questions_question_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions2.id'], name=op.f('answered_questions_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('answered_questions_pkey'))
    )
    # ### end Alembic commands ###
