"""add interview graph tables

Revision ID: f5d8c156cf7f
Revises: eb56d3facc65
Create Date: 2025-12-30 04:00:30.143783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f5d8c156cf7f'
down_revision: Union[str, Sequence[str], None] = 'eb56d3facc65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('termination_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_candidate_id'), 'interview_sessions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_thread_id'), 'interview_sessions', ['thread_id'], unique=False)
    op.create_table('extracted_skills',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('duration', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('depth', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('autonomy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('production_vs_prototype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_skills_name'), 'extracted_skills', ['name'], unique=False)
    op.create_index(op.f('ix_extracted_skills_session_id'), 'extracted_skills', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_skills_session_id'), table_name='extracted_skills')
    op.drop_index(op.f('ix_extracted_skills_name'), table_name='extracted_skills')
    op.drop_table('extracted_skills')
    op.drop_index(op.f('ix_interview_sessions_thread_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_candidate_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
